name: administrador
description: "A new Flutter project."
publish_to: 'none'

#03/09/2023
version: 1.0.3+4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^3.6.0
  firebase_core_platform_interface: ^5.3.0
  firebase_auth: ^5.3.1
  firebase_auth_platform_interface: ^7.4.7
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.2.1
  cloud_firestore: ^5.4.4
  url_launcher: ^6.1.6
  url_launcher_android: ^6.0.24
  email_validator: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  icons_launcher: ^3.0.0
  fluttertoast: ^8.0.0
  easy_search_bar: ^2.5.0
  dropdown_search: ^6.0.1
  flutter_typeahead: ^4.8.0
  firebase_analytics: ^11.3.3
  intl: ^0.19.0
  excel: ^4.0.6
  path: ^1.9.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
      background_color: "#FFFFF" # Azul
      adaptive_icon_background: "#FFFFFF" # Azul para ícones adaptativos
      adaptive_icon_foreground: "assets/logo.png"
    ios:
      enable: true
      background_color: "#FFFFFF" # Azul
    

# dart run icons_launcher:create

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
